COLLECTORS = "collectors"
COLLECTOR_MGR = "collector_manager"
COLLECTD_MGR = "collectd_manager"
FLUENTD_MGR = "fluentd_manager"
CONFIG_DATA = "config"
NODEMGR = "nodemgr_type"
ERROR = "error_msg"
ENABLED = "enabled"
NODES = "node_list"
TAGS = "tags"
TARGETS = "targets"
TARGET = "TARGET"
CONFIG = "config"
FAILED_LIST = "failed_list"
SUCCESS_LIST = "success_list"
SUCCESS_CONFIGS = "success_configs"
SUCCESS_PLUGIN_LIST = "success_plugin_list"
SUCCESS_TARGET_LIST = "success_targets_list"
SUPPORTED_PLUGINS = "supported_plugins"
SUPPORTED_TARGETS = "supported_targets"
COLLECTD_STATUS = "collectd_status"
COLLECTD_SERVICE = "collectd_service"
FLUENTD_STATUS = "fluentd_status"
FLUENTD_SERVICE = "fluentd_service"
VERSION = "version"
ACCESSLOG = "accessLog"
PROCESS = "process"
USER = "user"
PASSWORD = "password"
LOCATION = "location"
NODETYPE = "nodeType"
SECURE = "secure"

SALT = "salt"
COLLECTD = "collectd"
COLLECTOR = "collector_type"
ALL_CONF = "/*.conf"
ALL = "all"
DELETE = "delete"
FILTERS = "filters"
PLUGIN = "plugin"
OPTIONS = "Options"
EXTSN = ".conf"
INTERVAL = "interval"
NAME = "name"
PLUGINS = "plugins"
ELASTICSEARCH = "elasticsearch"
HOST = "host"
PORT = "port"
INDEX = "index"
SERVER_IP = "server_ip"
SERVER_PORT = "server_port"
CLIENT_IP = "client_ip"
CLIENT_PORT = "client_port"
TYPE = "type"
NODE_NAME = "node_name"
NO_RESP = "No Response"
RUNNING = "Running"
NOT_RUNNING = "Not Running"
META = "meta"

# operations
START = "start"
STOP = "stop"
RESTART = "restart"
STATUS = "status"
PUSH = "push"

# ERROR MESSAGES
EMPTY_NODE_LIST = "No nodes specified"
KEY_ERROR = " key not found"
ERROR_CFG_GEN = "Configuration generation failed"
DUMMY = "dummy"

# configurator api
METRICS = "metrics"
LOGGING = "logging"

HEARTBEAT = "heartbeat"
HEARTBEAT_INTERVAL = "heartbeat_interval"

COMPONENTS = "components"
DOCUMENT = "_doc"